# Generated by Django 5.0.6 on 2024-09-03 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='color_image')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product_image')),
                ('title', models.CharField(max_length=255, verbose_name='product title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='product title')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('in_sale', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_az', models.TextField(null=True)),
                ('new', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False, verbose_name='is published?')),
                ('category', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_manufacturer', to='product.manufacturer')),
            ],
            options={
                'verbose_name': 'Product ',
                'verbose_name_plural': 'Product ',
            },
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='product_images/')),
                ('in_stock', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity of the product')),
                ('color', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='product_version_color', to='product.color')),
                ('image', models.ManyToManyField(related_name='detailimage', to='product.images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_version', to='product.product')),
            ],
            options={
                'verbose_name': 'Product version',
                'verbose_name_plural': 'Product versions',
            },
        ),
    ]
