# Generated by Django 5.0.6 on 2024-09-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quality', models.PositiveBigIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('value', models.PositiveBigIntegerField()),
                ('nickname', models.CharField(max_length=100, verbose_name='Nickname')),
                ('summary', models.CharField(max_length=100, verbose_name='Nickname')),
                ('review', models.TextField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='product.product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
