# Generated by Django 5.0.6 on 2024-08-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_brand_remove_product_detail_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='color_name', to='product.color'),
        ),
    ]
