# Generated by Django 5.0.6 on 2024-08-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='cover_image',
            field=models.ImageField(upload_to='product_image/'),
        ),
    ]
