# Generated by Django 5.0.6 on 2024-08-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productversion_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='cover_image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
