# Generated by Django 5.0.6 on 2024-08-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productversion_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.AddField(
            model_name='product',
            name='old_proce',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
