# Generated by Django 5.0.6 on 2024-08-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_color_remove_product_old_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_proce',
            new_name='old_price',
        ),
    ]
