# Generated by Django 5.0.6 on 2024-08-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_manufacturer', to='product.manufacturer'),
        ),
    ]
