# Generated by Django 5.0.6 on 2024-09-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_description_az_product_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
    ]
