# Generated by Django 5.0.6 on 2024-06-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=255, verbose_name='first name')),
                ('lastname', models.CharField(max_length=255, verbose_name='last name')),
                ('company', models.CharField(max_length=255, verbose_name='name of company')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=255, verbose_name='name of city')),
                ('province', models.CharField(max_length=255, verbose_name='name of province')),
                ('zipcode', models.IntegerField(verbose_name='zip code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
