# Generated by Django 5.0.6 on 2024-09-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_basket_item_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
