# Generated by Django 5.0.6 on 2024-09-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_basket_item_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
