# Generated by Django 5.0.6 on 2024-09-03 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 character', max_length=100, verbose_name='Title of the author')),
                ('description', models.TextField(help_text='max 100 character', max_length=100, verbose_name='Description of the author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('types', models.CharField(max_length=20, verbose_name='Type of the blog')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 character', verbose_name='tag of blog')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 character', max_length=100, verbose_name='Title of the blog')),
                ('content', models.TextField(verbose_name='Content of the blog')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image for the blog', null=True, upload_to='blog/cover_image', verbose_name='Cover image of the blog')),
                ('author', models.ForeignKey(help_text='max 100 character', max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='author_of_blog', to='blog.author', verbose_name='Author of the blog')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogtype')),
                ('tags', models.ManyToManyField(max_length=10, related_name='tag_of_blog', to='blog.tags')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('coments', models.TextField(verbose_name='Bloga comment elave et: ')),
                ('name', models.CharField(max_length=255, verbose_name='Name: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email: ')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogs')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
