# Generated by Django 5.0.6 on 2024-06-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(max_length=10, related_name='tag_of_blog', to='blog.tags'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name of user')),
                ('email', models.EmailField(max_length=254, verbose_name='email of user')),
                ('comment', models.TextField(verbose_name='comment of the blog')),
                ('blog', models.ForeignKey(help_text='max 100 character', max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='comment_of_blog', to='blog.blogs', verbose_name='Comment of the blog')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
