# Generated by Django 5.0.6 on 2024-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_tags_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
