# Generated by Django 5.0.6 on 2024-09-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogs_types_blogs_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='types',
        ),
        migrations.AddField(
            model_name='blogs',
            name='types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogtype'),
            preserve_default=False,
        ),
    ]
