# Generated by Django 5.0.6 on 2024-09-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogs_types_blogs_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='blogtype',
            name='types',
        ),
        migrations.RemoveField(
            model_name='blogtype',
            name='updated',
        ),
        migrations.AddField(
            model_name='blogtype',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
