# Generated by Django 5.0.6 on 2024-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for the blog', null=True, upload_to='blog/cover_image', verbose_name='Cover image of the blog'),
        ),
    ]
