# Generated by Django 5.0.6 on 2024-07-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogs_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default=1, verbose_name='message'),
            preserve_default=False,
        ),
    ]
