# Generated by Django 5.0.6 on 2024-08-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contactus_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('types', models.CharField(max_length=20, verbose_name='Type of the blog')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='about',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blog_id',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog_type',
        ),
        migrations.AddField(
            model_name='blogs',
            name='types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogtype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
