# Generated by Django 5.0.6 on 2024-09-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtype_remove_blogs_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_id',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
