# Generated by Django 5.0.6 on 2024-08-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_full_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
