# Generated by Django 5.0.6 on 2024-07-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_alter_cart_price_alter_cart_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
